export const resources = {
  students: {
    table: 'students',
    columns: ['id', 'student_code', 'full_name', 'email', 'course_id', 'enrollment_year', 'status', 'created_at', 'updated_at'],
    writable: ['student_code', 'full_name', 'email', 'course_id', 'enrollment_year', 'status'],
    required: ['student_code', 'full_name', 'email'],
    search: ['student_code', 'full_name', 'email'],
    filters: ['course_id', 'status', 'enrollment_year'],
    sort: ['id', 'student_code', 'full_name', 'email', 'enrollment_year', 'created_at'],
  },
  teachers: {
    table: 'teachers',
    columns: ['id', 'employee_code', 'full_name', 'email', 'department', 'status', 'created_at', 'updated_at'],
    writable: ['employee_code', 'full_name', 'email', 'department', 'status'],
    required: ['employee_code', 'full_name', 'email'],
    search: ['employee_code', 'full_name', 'email', 'department'],
    filters: ['status', 'department'],
    sort: ['id', 'employee_code', 'full_name', 'department', 'created_at'],
  },
  courses: {
    table: 'courses',
    columns: ['id', 'course_code', 'name', 'department', 'status', 'created_at', 'updated_at'],
    writable: ['course_code', 'name', 'department', 'status'],
    required: ['course_code', 'name'],
    search: ['course_code', 'name', 'department'],
    filters: ['status', 'department'],
    sort: ['id', 'course_code', 'name', 'department', 'created_at'],
  },
  subjects: {
    table: 'subjects',
    columns: ['id', 'course_id', 'subject_code', 'name', 'term', 'status', 'created_at', 'updated_at'],
    writable: ['course_id', 'subject_code', 'name', 'term', 'status'],
    required: ['course_id', 'subject_code', 'name'],
    search: ['subject_code', 'name', 'term'],
    filters: ['course_id', 'status', 'term'],
    sort: ['id', 'subject_code', 'name', 'term', 'created_at'],
  },
  'feedback-questions': {
    table: 'feedback_questions',
    columns: ['id', 'prompt', 'question_type', 'options', 'is_required', 'status', 'created_at', 'updated_at'],
    writable: ['prompt', 'question_type', 'options', 'is_required', 'status'],
    required: ['prompt', 'question_type'],
    search: ['prompt', 'question_type'],
    filters: ['question_type', 'status', 'is_required'],
    sort: ['id', 'prompt', 'question_type', 'created_at'],
  },
  'feedback-forms': {
    table: 'feedback_forms',
    columns: ['id', 'title', 'description', 'course_id', 'subject_id', 'teacher_id', 'opens_at', 'closes_at', 'status', 'created_at', 'updated_at'],
    writable: ['title', 'description', 'course_id', 'subject_id', 'teacher_id', 'opens_at', 'closes_at', 'status'],
    required: ['title', 'course_id', 'subject_id', 'teacher_id'],
    search: ['title', 'description'],
    filters: ['course_id', 'subject_id', 'teacher_id', 'status'],
    sort: ['id', 'title', 'opens_at', 'closes_at', 'created_at'],
  },
  'feedback-responses': {
    table: 'feedback_responses',
    columns: ['id', 'form_id', 'submitted_at'],
    writable: [],
    required: [],
    search: ['id', 'form_id'],
    filters: ['form_id'],
    sort: ['id', 'form_id', 'submitted_at'],
  },
  users: {
    table: 'users',
    columns: ['id', 'role_id', 'full_name', 'email', 'status', 'created_at', 'updated_at'],
    writable: ['role_id', 'full_name', 'email', 'password_hash', 'status'],
    required: ['role_id', 'full_name', 'email'],
    search: ['full_name', 'email'],
    filters: ['role_id', 'status'],
    sort: ['id', 'full_name', 'email', 'created_at'],
  },
  roles: {
    table: 'roles',
    columns: ['id', 'name', 'description', 'created_at', 'updated_at'],
    writable: ['name', 'description'],
    required: ['name'],
    search: ['name', 'description'],
    filters: [],
    sort: ['id', 'name', 'created_at'],
  },
};

export const resourceNames = Object.keys(resources);